version: '3.8'

services:
  bookstore-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-test:
    image: alpine/curl
    depends_on:
      - bookstore-api
    command: ["sh", "-c", "sleep 10 && curl -f http://bookstore-api:8080/api/hello"]
    restart: "no"