basePath: /
host: localhost:8000
info:
  contact:
    email: '[email protected]'
    name: API Support
    url: http://www.swagger.io/support
  description: REST API для онлайн-магазина книг
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: BookStore Backend API
  version: 1.0.0
paths: {}
schemes:
- http
- https
swagger: "2.0"
