name: CI/CD for Bookstore Backend

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test API
      run: |
        go run ./cmd/api/main.go &
        sleep 5
        curl -f http://localhost:8080/api/hello
        curl -f http://localhost:8080/health

    - name: Build Docker image
      run: docker build -t bookstore-api:latest .

    - name: Test Docker container
      run: |
        docker run -d -p 8080:8080 --name test-api bookstore-api:latest
        sleep 5
        docker ps
        curl -f http://localhost:8080/api/hello
        docker stop test-api

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render
      run: |
        echo "Деплой на Render будет настроен через webhook"
        echo "Сборка прошла успешно, можно деплоить"
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}